# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da11f75d5eb270b26de1fe844c12a2d3b902797596057a2fb0e4bd9fb2b8729389ed0a527510ac2f6e818d32f833c743c47c0de8b3592f869ef343abcf921e1e

test:
  secret_key_base: 4c3b8b9a24edcdfd7247f8c42ac89d00bd02d7c2f19d07f8d56a5c9bf1e192019c88178d4c07629b350282b940dc3e477916ab126d18c55a9e37954e528e181c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
